[package]
name = "Whatinizer"
version = "1.0.0"
edition = "2018"
authors = ["Veinhelm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
